-- Advisory · model_portfolios — catalogue (list/get) + per-client recommendation
-- GENERATED by python/rm-demo/src/generate_sql.py — do not edit by hand.
-- Idempotent: CREATE TABLE IF NOT EXISTS + INSERT … ON CONFLICT DO NOTHING.

CREATE TABLE IF NOT EXISTS model_catalog (
  id   INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  data JSONB NOT NULL
);
INSERT INTO model_catalog (id, data) VALUES (1, $rmj${"house": "ABC Wealth Management", "as_of": "2026-06-20", "count": 4, "models": [{"code": "CP-1", "name": "Capital Preservation", "risk_band": "conservative", "reference_currency": "CHF", "expected_return_pa": 2.8, "volatility_pa": 3.5, "expected_max_drawdown": 3, "rebalancing": "quarterly"}, {"code": "BI-3", "name": "Balanced Income", "risk_band": "balanced-conservative", "reference_currency": "CHF", "expected_return_pa": 4.8, "volatility_pa": 7.2, "expected_max_drawdown": 7, "rebalancing": "quarterly"}, {"code": "BG-5", "name": "Balanced Growth", "risk_band": "balanced", "reference_currency": "USD", "expected_return_pa": 6, "volatility_pa": 9.5, "expected_max_drawdown": 12, "rebalancing": "quarterly"}, {"code": "GR-7", "name": "Growth", "risk_band": "growth", "reference_currency": "USD", "expected_return_pa": 7.5, "volatility_pa": 13, "expected_max_drawdown": 20, "rebalancing": "semi-annual"}]}$rmj$::jsonb) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS model_portfolios (
  code TEXT PRIMARY KEY,
  data JSONB NOT NULL
);
INSERT INTO model_portfolios (code, data) VALUES ($rmt$CP-1$rmt$, $rmj${"house": "ABC Wealth Management", "as_of": "2026-06-20", "code": "CP-1", "name": "Capital Preservation", "risk_band": "conservative", "reference_currency": "CHF", "expected_return_pa": 2.8, "volatility_pa": 3.5, "expected_max_drawdown": 3, "rebalancing": "quarterly", "eligible": "Capital preservation; risk profile 1-2/7", "allocation": [{"asset_class": "Equities", "weight": 15}, {"asset_class": "Fixed income", "weight": 70}, {"asset_class": "Alternatives", "weight": 8}, {"asset_class": "Cash", "weight": 7}]}$rmj$::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO model_portfolios (code, data) VALUES ($rmt$BI-3$rmt$, $rmj${"house": "ABC Wealth Management", "as_of": "2026-06-20", "code": "BI-3", "name": "Balanced Income", "risk_band": "balanced-conservative", "reference_currency": "CHF", "expected_return_pa": 4.8, "volatility_pa": 7.2, "expected_max_drawdown": 7, "rebalancing": "quarterly", "eligible": "Stable growth / capital preservation; risk profile 3/7", "allocation": [{"asset_class": "Equities", "weight": 38}, {"asset_class": "Fixed income", "weight": 45}, {"asset_class": "Alternatives", "weight": 10}, {"asset_class": "Cash", "weight": 7}]}$rmj$::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO model_portfolios (code, data) VALUES ($rmt$BG-5$rmt$, $rmj${"house": "ABC Wealth Management", "as_of": "2026-06-20", "code": "BG-5", "name": "Balanced Growth", "risk_band": "balanced", "reference_currency": "USD", "expected_return_pa": 6, "volatility_pa": 9.5, "expected_max_drawdown": 12, "rebalancing": "quarterly", "eligible": "Growth with moderate risk; risk profile 4-5/7", "allocation": [{"asset_class": "Equities", "weight": 55}, {"asset_class": "Fixed income", "weight": 30}, {"asset_class": "Alternatives", "weight": 12}, {"asset_class": "Cash", "weight": 3}]}$rmj$::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO model_portfolios (code, data) VALUES ($rmt$GR-7$rmt$, $rmj${"house": "ABC Wealth Management", "as_of": "2026-06-20", "code": "GR-7", "name": "Growth", "risk_band": "growth", "reference_currency": "USD", "expected_return_pa": 7.5, "volatility_pa": 13, "expected_max_drawdown": 20, "rebalancing": "semi-annual", "eligible": "Long-term growth; risk profile 6-7/7", "allocation": [{"asset_class": "Equities", "weight": 75}, {"asset_class": "Fixed income", "weight": 12}, {"asset_class": "Alternatives", "weight": 10}, {"asset_class": "Cash", "weight": 3}]}$rmj$::jsonb) ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS model_recommend (
  client_id TEXT PRIMARY KEY,
  data      JSONB NOT NULL
);
INSERT INTO model_recommend (client_id, data) VALUES ($rmt$PTY-0002005$rmt$, $rmj${"model": "BI-3", "note": "Stable growth / capital preservation; BI-3 max DD 7% ABOVE stated 5% — propose risk-reduced variant."}$rmj$::jsonb) ON CONFLICT (client_id) DO NOTHING;
INSERT INTO model_recommend (client_id, data) VALUES ($rmt$PTY-0002002$rmt$, $rmj${"model": "CP-1", "note": "Conservative (2/7), capital preservation, education liquidity bucket."}$rmj$::jsonb) ON CONFLICT (client_id) DO NOTHING;
INSERT INTO model_recommend (client_id, data) VALUES ($rmt$PTY-0003001$rmt$, $rmj${"model": "BI-3", "note": "Conservative discretionary; 45% IG / 25% min-vol equity aligns with agreed IPS."}$rmj$::jsonb) ON CONFLICT (client_id) DO NOTHING;
INSERT INTO model_recommend (client_id, data) VALUES ($rmt$CH-PB-0049217$rmt$, $rmj${"model": "BG-5", "note": "Balanced (4/6), modest growth; current allocation slightly equity-heavy vs model."}$rmj$::jsonb) ON CONFLICT (client_id) DO NOTHING;
INSERT INTO model_recommend (client_id, data) VALUES ($rmt$CH-PB-0061884$rmt$, $rmj${"model": "GR-7", "note": "Growth (5/6), 15+ year horizon; alternatives sleeve actively managed."}$rmj$::jsonb) ON CONFLICT (client_id) DO NOTHING;
INSERT INTO model_recommend (client_id, data) VALUES ($rmt$CH-PROS-0118$rmt$, $rmj${"model": null, "note": "UHNW prospect — consolidation scenario; risk profile TBD."}$rmj$::jsonb) ON CONFLICT (client_id) DO NOTHING;
INSERT INTO model_recommend (client_id, data) VALUES ($rmt$CH-PROS-0119$rmt$, $rmj${"model": "GR-7", "note": "Growth (5/6), 10yr+ horizon; globally diversified SAA, thematic technology capped at 5% to avoid re-concentration."}$rmj$::jsonb) ON CONFLICT (client_id) DO NOTHING;
INSERT INTO model_recommend (client_id, data) VALUES ($rmt$GB-PB-0072001$rmt$, $rmj${"model": "BG-5", "note": "Balanced Growth (GBP); trim Mag-7 to mandate (aggregate 20%, clear NVDA/MSFT cap breaches) and redeploy to broaden equity + income."}$rmj$::jsonb) ON CONFLICT (client_id) DO NOTHING;

