repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.10
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      exclude: ^unique_toolkit/docs/\.python_files/.*|^unique_toolkit/docs/examples_from_docs/.*
    # Sort imports
    - id: ruff
      args: ["check", "--select", "I", "--fix"]
      exclude: ^unique_toolkit/docs/\.python_files/.*|^unique_toolkit/docs/examples_from_docs/.*
    # Run the formatter.
    - id: ruff-format
      exclude: ^unique_toolkit/docs/\.python_files/.*|^unique_toolkit/docs/examples_from_docs/.*