repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Sort imports
    - id: ruff
      args: ["check", "--select", "I", "--fix"]
    # Run the formatter.
    - id: ruff-format