# generated by datamodel-codegen:
#   filename:  open-api.yaml
#   timestamp: 2025-06-10T08:06:23+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Field, RootModel


class Pet(BaseModel):
    id: int
    name: str
    tag: str | None = None


class Pets(RootModel[list[Pet]]):
    root: list[Pet]


class Error(BaseModel):
    code: int
    message: str


class Api(BaseModel):
    api_key: str | None = Field(
        None, alias="apiKey", description="To be used as a dataset parameter value"
    )
    api_version_number: str | None = Field(
        None,
        alias="apiVersionNumber",
        description="To be used as a version parameter value",
    )
    api_url: AnyUrl | None = Field(
        None, alias="apiUrl", description="The URL describing the dataset's fields"
    )
    api_documentation_url: AnyUrl | None = Field(
        None,
        alias="apiDocumentationUrl",
        description="A URL to the API console for each API",
    )


class Apis(RootModel[list[Api]]):
    root: list[Api]


class PetsGetParametersQuery(BaseModel):
    limit: int | None = None
