version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "10100:5432"
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgress -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
