[pytest]
addopts = --strict-markers --import-mode=importlib
asyncio_mode = auto
markers =
    asyncio: for async tests
    unit: for unit tests
    serial
filterwarnings =
    ignore:DeprecationWarning