name: 'Publish to PyPI with Poetry'
description: 'Builds and publishes a Python package to PyPI using Poetry'

inputs:
  package_dir:
    description: 'Path to the package directory (e.g., ./unique_sdk)'
    required: true
  package_name:
    description: 'Package name on PyPI (for version checking)'
    required: true
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  poetry_version:
    description: 'Poetry version to install'
    required: false
    default: '1.8.3'
  check_version:
    description: 'Check if version already exists on PyPI before publishing'
    required: false
    default: 'true'
  pypi_token:
    description: 'PyPI API token for publishing'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Poetry
      shell: bash
      run: |
        POETRY_VERSION='${{ inputs.poetry_version }}'
        PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install poetry==$POETRY_VERSION

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: poetry install

    - name: Build Package
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: poetry build

    - name: Get version
      id: get_version
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: |
        VERSION=$(poetry version -s)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Package version: $VERSION"

    - name: Check PyPI version and publish
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ inputs.pypi_token }}
      run: |
        CURRENT_VERSION="${{ steps.get_version.outputs.version }}"
        
        if [ "${{ inputs.check_version }}" = "true" ]; then
          LATEST_VERSION=$(curl -s https://pypi.org/pypi/${{ inputs.package_name }}/json | jq -r '.info.version' 2>/dev/null || echo "0.0.0")
          if [ "$LATEST_VERSION" = "null" ]; then
            LATEST_VERSION="0.0.0"
          fi
          
          if [ "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
            echo "Version $CURRENT_VERSION already exists on PyPI. Skipping publish."
            exit 0
          fi
        fi
        
        echo "Publishing $CURRENT_VERSION to PyPI..."
        poetry publish
