#!/usr/bin/env python3
"""Generate Helm chart artifacts from Pydantic provider settings.

Writes (chart-local, owned by this generator):
  - deploy/helm-chart/values.additional.schema.json
  - deploy/helm-chart/templates/_generated.tpl
  - deploy/helm-chart/values.yaml  (only the @helm-gen:providers region)

Does NOT write values.schema.json — that is merged from the shared base chart
by ``scripts/render-values-schema.sh`` at the ai repo root (run after this).

Does NOT write README.md — that is generated by ``scripts/render-helm-docs.sh``
at the ai repo root (run after render-values-schema.sh).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHART_DIR = ROOT / "deploy" / "helm-chart"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from unique_search_proxy_client.web.helm.generator import (  # noqa: E402
    check_artifacts,
    write_artifacts,
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 when generated artifacts drift from committed files.",
    )
    args = parser.parse_args()

    if args.check:
        drift = check_artifacts(CHART_DIR)
        if drift:
            for line in drift:
                print(line, file=sys.stderr)
            print(
                "\nError: Helm generated artifacts are out of sync.",
                file=sys.stderr,
            )
            print(
                "Run: uv run python scripts/generate_helm_config.py",
                file=sys.stderr,
            )
            return 1
        print("All Helm generated artifacts are in sync.")
        return 0

    written = write_artifacts(CHART_DIR)
    for name, path in sorted(written.items()):
        print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
