# tool_prompts.py — GENERATED by python/rm-demo/src/generate_tool_prompts.py
# from resources/unique/MCP_SERVERS.md. DO NOT EDIT BY HAND — edit the MD and re-run.
#
"""Per-tool Unique AI prompt metadata for the `RM Agent - Advisory` connector.

Unique reads these two keys off each MCP tool's ``_meta`` and renders them as the
tool's "System Prompt: Tool Usage Instructions" and "System Prompt: Tool Response
Format Instructions" (unique_mcp MetaKeys: UNIQUE_AI_TOOL_SYSTEM_PROMPT /
UNIQUE_AI_TOOL_FORMAT_INFORMATION). Attach them via :func:`tool_meta`.
"""

SYSTEM_PROMPT_META_KEY = "unique.app/system-prompt"
FORMAT_INFO_META_KEY = "unique.app/tool-format-information"

TOOL_PROMPTS = {
    "get_attribution": {
        "system_prompt": "Input: a client name or client_id. Use to explain what drove performance.",
        "format": "Returns `{client_id, contribution_by_position[], contribution_by_asset_class[], top_contributors[], top_detractors[]}`. Clients with no attribution (e.g. prospects) return `{client_id, error}` instead.",
    },
    "get_cio_themes": {
        "system_prompt": "No arguments. Bank-wide.",
        "format": "Returns `{house, as_of, valid_until, count, themes:[{theme, horizon, conviction, rationale}]}`.",
    },
    "get_corporate_actions": {
        "system_prompt": "Input: a client name or client_id. Use for corporate actions on the client's holdings.",
        "format": "Returns `{client_id, count, items:[{id,ticker,isin,type,status,ex_date,pay_date,gross_per_share|gross_amount|call_amount,currency,note}]}`. Flag any `status:\"pending_election\"` that needs a client instruction.",
    },
    "get_coverage_scenario": {
        "system_prompt": "Input (object): `{client_id|client, scenario_id}`. Resolve the client via `RM Agent - CRM` first (pass the client NAME or party id). `scenario_id` ∈ `baseline | cash_topup_100k | partial_repay_200k | trim_collateral_200k | hold`. Use to project how a Lombard facility's coverage changes under a restoration action. ALWAYS state the projected coverage % and the buffer to the margin trigger, and flag any facility in/near a margin call explicitly. Non-advisory — curing/amending is an RM + Credit decision.",
        "format": "Returns `{client_id, scenario_id, baseline{coverage_pct,band,…}, projected{coverage_pct,band,lending_value,loan_outstanding,headroom}, narrative, compliance_notes, options[{scenario_id, label, projected_coverage_pct, band, selected}]}`. Bands: `margin/warning/safe`. Lead with the projected coverage % + band and the recommended action; INDICATIVE demo data — never books a trade.",
    },
    "get_elections": {
        "system_prompt": "Input: a client name or client_id. Use for voluntary corporate-action elections.",
        "format": "Returns `{client_id, count, items:[{id,linked_corporate_action,ticker,type,options[],elected,election_deadline,status,recommended,note}]}`. Surface open elections + their deadlines and state the recommended option.",
    },
    "get_holdings": {
        "system_prompt": "Input: a client name or client_id. Use for the current custodied portfolio.",
        "format": "Returns `{client_id, account_id, reporting_currency, as_of, total_market_value, positions[{ticker,asset_class,market_value,currency,weight_pct,...}], held_away_assets[]}`. Always cite `total_market_value` + `as_of`; keep custodied positions separate from held-away.",
    },
    "get_house_view": {
        "system_prompt": "No arguments for the full view, or pass an asset class (equities / fixed income / alternatives / fx / cash) to filter. Bank-wide — no client_id.",
        "format": "Returns `{house, as_of, valid_until, count, views:[{asset_class, stance, conviction, rationale}]}` (or a single asset-class object). Always quote `as_of` / `valid_until`.",
    },
    "get_model_portfolio": {
        "system_prompt": "Input: a model code/name ('BI-3', 'Balanced Income') or a risk band (conservative / balanced-conservative / balanced / growth).",
        "format": "Returns the full model `{code,name,risk_band,reference_currency,allocation[{asset_class,weight}],expected_return_pa,volatility_pa,expected_max_drawdown,rebalancing,eligible}`.",
    },
    "get_orders": {
        "system_prompt": "Input: a client name or client_id. Use for proposed / working / filled orders.",
        "format": "Returns `{client_id, count, items:[{id,ticker,side,order_type,quantity?,gross_amount,currency,status,placed,filled?,pre_trade_compliance,note}]}`. Always show `pre_trade_compliance` and `status`.",
    },
    "get_performance": {
        "system_prompt": "Input: a client name or client_id. Use for time-weighted returns.",
        "format": "Returns `{client_id, basis, periods{MTD/QTD/YTD{gross,net,benchmark?,relative?}}, since_inception{...}, benchmark_name}`. Always present net alongside gross, plus the benchmark / relative where given.",
    },
    "get_portfolio_transactions": {
        "system_prompt": "Input: a client name or client_id. Use for the client's settled transaction history.",
        "format": "Returns `{client_id, count, items:[{trade_date,type,ticker?,gross_amount,currency,counterparty?,status}]}`. Settled activity only, chronological.",
    },
    "get_risk_exposure": {
        "system_prompt": "Input: a client name or client_id. Use for allocation-vs-target and risk flags.",
        "format": "Returns `{client_id, asset_allocation[{asset_class,actual_pct,target_pct}], flags[], currency_exposure{} (present for some clients)}`. Surface `flags` (overweights, concentrations) explicitly.",
    },
    "get_tactical_calls": {
        "system_prompt": "No arguments. Bank-wide.",
        "format": "Returns `{house, as_of, valid_until, count, calls:[{dimension, call, detail, magnitude, conviction, rationale}]}`.",
    },
    "get_tax_lots": {
        "system_prompt": "Input: a client name or client_id. Use for tax lots, cost basis, and tax impact.",
        "format": "Returns `{client_id, lots:[{isin,ticker,acquired,quantity?,cost_total,market_value,unrealised,currency,note?}], unrealised_gain_loss{total,currency}, estimated_transaction_cost, estimated_tax_impact, note}`. Note the CH private-investor CGT exemption where the data states it.",
    },
    "get_transaction_monitoring": {
        "system_prompt": "Input: a client name or client_id. Use for AML / transaction-monitoring status.",
        "format": "Returns `{client_id, alerts:[{id,date,type,amount,currency,rule,disposition,source_of_wealth|purpose,cleared_by,cleared_date}], open_cases, status, note?}`. Present alerts and disposition factually; `cleared` means resolved.",
    },
    "list_model_portfolios": {
        "system_prompt": "No arguments. Use for the model catalogue.",
        "format": "Returns `{house, as_of, count, models:[{code,name,risk_band,reference_currency,expected_return_pa,volatility_pa,expected_max_drawdown,rebalancing}]}`.",
    },
    "recommend_model": {
        "system_prompt": "Input: a client name or client_id (resolved via the CRM mandate on `RM Agent - CRM`).",
        "format": "Returns `{client_id, model, note}` — `model` is the recommended model code (e.g. BG-5) and `note` is the suitability note (states if the model's expected max drawdown exceeds the client's stated tolerance).",
    },
    "Reset_Demo_Data": {
        "system_prompt": "No input. Operator/demo tool only — call BETWEEN demo runs to restore the baseline. Never call it as part of answering a client question.",
        "format": "Returns `{reset:true, tables:{...row counts...}, total_rows, note}`. Confirm the reset succeeded and the row counts look right; do not surface to the client.",
    },
}


def tool_meta(name, base=None):
    """Merge a tool's existing meta (e.g. its icon) with its Usage / Response-Format
    system-prompt metadata so Unique AI shows them as the tool's instructions.
    Returns the merged dict, or None when there is nothing to attach."""
    meta = dict(base or {})
    prompts = TOOL_PROMPTS.get(name)
    if prompts:
        if prompts.get("system_prompt"):
            meta[SYSTEM_PROMPT_META_KEY] = prompts["system_prompt"]
        if prompts.get("format"):
            meta[FORMAT_INFO_META_KEY] = prompts["format"]
    return meta or None
