name: 'Setup Python and Poetry'
description: 'Sets up Python 3.11 and installs Poetry 1.8.3'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  poetry-version:
    description: 'Poetry version to install'
    required: false
    default: '1.8.3'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      shell: bash
      run: |
        POETRY_VERSION='${{ inputs.poetry-version }}'
        PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install poetry==$POETRY_VERSION

