-- CRM · client_memory — editable talking points / open questions / documents (per client)
-- GENERATED by python/rm_mcps_export/generate_sql.py — do not edit by hand.
-- Idempotent: CREATE TABLE IF NOT EXISTS + INSERT … ON CONFLICT DO NOTHING.

CREATE TABLE IF NOT EXISTS rm_talking_points (
  client_id TEXT, position INT, text TEXT, PRIMARY KEY (client_id, position)
);
CREATE TABLE IF NOT EXISTS rm_open_questions (
  client_id TEXT, position INT, text TEXT, PRIMARY KEY (client_id, position)
);
CREATE TABLE IF NOT EXISTS rm_documents (
  client_id TEXT, position INT, title TEXT, "contentId" TEXT, PRIMARY KEY (client_id, position)
);

INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 1, $rmt$Walk through how the portfolio behaves in a drawdown — her anchor is the 5% ceiling.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 2, $rmt$Present the Conservative CHF Composite and house-view rationale.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 3, $rmt$Confirm transfer timing from Privatbank Lindengut (~CHF 10m on signature).$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 4, $rmt$Discuss fee structure and reporting cadence.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 5, $rmt$Agree next steps post tax-adviser review.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 1, $rmt$Confirm investment horizon — discovery suggests 7–10 years.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 2, $rmt$Any liquidity needs in the next 24 months?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 3, $rmt$ESG preferences or exclusions to apply?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 4, $rmt$Full CHF 10m at signing, or phased deployment?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002005$rmt$, 1, $rmt$Client narrative brief$rmt$, $rmt$cont_rqrgkp83ndzwxlcj30b17qr0$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002005$rmt$, 2, $rmt$Custody statement — Privatbank Lindengut (Apr 2026)$rmt$, $rmt$cont_b2bnkp306j9k8gyam7jwq56v$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002005$rmt$, 3, $rmt$Client profile$rmt$, $rmt$cont_xlk85cp62jmfxwp22vk49jlw$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 1, $rmt$Explain the conservative deployment plan from 100% cash.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 2, $rmt$Define the education liquidity bucket size and placement.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 3, $rmt$Walk through CP-1 model allocation and expected behaviour.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 4, $rmt$Confirm no complex/structured products constraint.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 5, $rmt$Agree implementation timeline (lump-sum vs phased).$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 1, $rmt$Lump-sum deployment or phased entry over 3–6 months?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 2, $rmt$Size of education liquidity bucket (CHF amount)?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 3, $rmt$Any ESG preferences beyond the default?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 4, $rmt$Confirm risk-profiling questionnaire on file.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002002$rmt$, 1, $rmt$Client narrative brief$rmt$, $rmt$cont_drpga9o610x841vk8r1itlux$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002002$rmt$, 2, $rmt$Account statement — inherited assets (UBS)$rmt$, $rmt$cont_br08w6ech3sid1jel2chmnrz$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002002$rmt$, 3, $rmt$Inheritance tax confirmation — Kt. Zürich$rmt$, $rmt$cont_bsq99pieh1w86gvtf5a4fxvf$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 1, $rmt$Confirm onboarding document checklist sent.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 2, $rmt$Walk through the agreed strategic asset allocation.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 3, $rmt$Explain the 5% drawdown trigger and de-risking protocol.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 4, $rmt$Tobacco exclusion — note legacy BAT in held-away portfolio.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 5, $rmt$Timeline for funding the USD 10m tranche post-KYC.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 1, $rmt$2019 sale documents from Hollis & Crane — received in full?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 2, $rmt$Trust documentation pack for Ellery Family Settlement?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 3, $rmt$FX conversion timing GBP → USD on funding?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 4, $rmt$Future review of ~£24m held-away portfolio?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0003001$rmt$, 1, $rmt$Investment policy statement$rmt$, $rmt$cont_hc3vxm336ekdbftvz7kd3q9v$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0003001$rmt$, 2, $rmt$Existing portfolio statement$rmt$, $rmt$cont_eak77uu8frd8lgcjhs2runlr$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0003001$rmt$, 3, $rmt$CIO house view$rmt$, $rmt$cont_hc9frb8z0l1oufm0x4zvpe1b$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 1, $rmt$Address Lombard coverage warning — Apple-driven breach 22 Jun.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 2, $rmt$Present two education mandate variants (5–8 yr horizon).$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 3, $rmt$ESG vs conventional comparison for balanced profile.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 4, $rmt$Zug property financing — mortgage indicative offer status.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 5, $rmt$Rebalance toward BG-5 model weights.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 1, $rmt$Kaufvertrag and Grundbuchauszug for mortgage offer?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 2, $rmt$Education sub-mandate size and funding source?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 3, $rmt$ESG overlay preference — partial or full?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 4, $rmt$Held-away wealth / share-of-wallet conversation?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PB-0049217$rmt$, 1, $rmt$Client profile$rmt$, $rmt$cont_ej8sf4bpb7wy7ph8mcvbb5n5$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 1, $rmt$Review PE med-tech commitment pipeline — client wants to be consulted.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 2, $rmt$Philanthropy cadence — recent CHF 1.0m grant to Fondation Lavanchy.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 3, $rmt$Succession governance at Lavanchy Patrimoine SA.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 4, $rmt$Alternatives sleeve performance and rebalancing.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 5, $rmt$Lombard facility review outcome.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 1, $rmt$Next PE med-tech commitment — timing and sizing?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 2, $rmt$Succession planning timeline for holding company?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 3, $rmt$Philanthropy grant schedule for H2 2026?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 4, $rmt$Any changes to approved-shelf alternatives list?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PB-0061884$rmt$, 1, $rmt$Client profile$rmt$, $rmt$cont_k2hzvd9oq2d4ux0488mbxqtd$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 1, $rmt$Frame the consolidation value proposition vs incumbent.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 2, $rmt$CH/IT cross-border structuring — flag for Compliance.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 3, $rmt$Multi-generational wealth and governance needs.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 4, $rmt$Alternatives and private-markets capabilities.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 5, $rmt$Relationship model — senior RM continuity.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 1, $rmt$Tax residence confirmation (CH/IT)?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 2, $rmt$Scope of assets available for transfer?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 3, $rmt$Mandate type preference (discretionary vs advisory)?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 4, $rmt$Timeline and decision process with incumbent providers?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PROS-0118$rmt$, 1, $rmt$Prospect profile$rmt$, $rmt$cont_pc5npyb4qq89cx3grhsdikk9$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PROS-0118$rmt$, 2, $rmt$Prospect data pack$rmt$, $rmt$cont_z6v2aceyafz4axlwgbdnk1a4$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0119$rmt$, 1, $rmt$Phasing: baseline nine-month averaging vs accelerated five-month — recommend baseline from all-cash.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0119$rmt$, 2, $rmt$Private-markets sleeve (14%): Claire to present 3–4 fund commitments (CHF 0.5–1.0m each).$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0119$rmt$, 3, $rmt$Thematic technology capped at 5% — express conviction without rebuilding concentration.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0119$rmt$, 4, $rmt$USD escrow (~USD 4m) releases Q4 2026 — staged FX conversion, ~50% hedged.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0119$rmt$, 5, $rmt$Zug tax framing: 2024 sale exempt private gain; ongoing income / wealth tax modest but recurring.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0119$rmt$, 1, $rmt$Phasing variant — baseline (nine months) or accelerated (five months)?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0119$rmt$, 2, $rmt$Private-markets shortlist — confirm strategies, managers and sizing?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0119$rmt$, 3, $rmt$Apply the MSCI ESG-aligned tilt at outset?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0119$rmt$, 4, $rmt$USD escrow on release — top up the mandate or hold in operating cash?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PROS-0119$rmt$, 1, $rmt$Client profile & source of wealth$rmt$, $rmt$cont_j08b2prlpbld6ctn8q1jp62k$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PROS-0119$rmt$, 2, $rmt$Investment proposal — CHF 20m mandate$rmt$, $rmt$cont_lt4lvopokjrw7fp2clmwfkef$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$GB-PB-0072001$rmt$, 1, $rmt$Mag-7 drift is performance-driven (NVDA / META), not strategy — aggregate 29.5% vs 20% target.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$GB-PB-0072001$rmt$, 2, $rmt$NVDA 7.2% and MSFT 5.5% breach the 5% single-name cap — both trimmed to clear.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$GB-PB-0072001$rmt$, 3, $rmt$CGT is the point requiring explicit acknowledgement — est. GBP 60k–80k on the full programme.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$GB-PB-0072001$rmt$, 4, $rmt$Redeploy GBP 771,875: global ex-US, quality dividend, UK/European value, cash reserve.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$GB-PB-0072001$rmt$, 5, $rmt$Staged execution over three sessions; option to split across the tax-year boundary.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$GB-PB-0072001$rmt$, 1, $rmt$Acknowledge the CGT impact (GBP 60k–80k) before execution?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$GB-PB-0072001$rmt$, 2, $rmt$Defer part of the programme into the next tax year (post 6 April)?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$GB-PB-0072001$rmt$, 3, $rmt$Retain any higher NVDA exposure (30-day matching rule applies if rebuilt)?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$GB-PB-0072001$rmt$, 4, $rmt$Confirm the redeployment split across the three destination sleeves?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$GB-PB-0072001$rmt$, 1, $rmt$Rebalancing proposal — Magnificent-7 trim$rmt$, $rmt$cont_o34m9zyhao51p7cq44wljfjp$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
