-- CRM · client_memory — editable talking points / open questions / documents (per client)
-- GENERATED by python/rm_mcps_export/generate_sql.py — do not edit by hand.
-- Idempotent: CREATE TABLE IF NOT EXISTS + INSERT … ON CONFLICT DO NOTHING.

CREATE TABLE IF NOT EXISTS rm_talking_points (
  client_id TEXT, position INT, text TEXT, PRIMARY KEY (client_id, position)
);
CREATE TABLE IF NOT EXISTS rm_open_questions (
  client_id TEXT, position INT, text TEXT, PRIMARY KEY (client_id, position)
);
CREATE TABLE IF NOT EXISTS rm_documents (
  client_id TEXT, position INT, title TEXT, "contentId" TEXT, PRIMARY KEY (client_id, position)
);

INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 1, $rmt$Walk through how the portfolio behaves in a drawdown — her anchor is the 5% ceiling.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 2, $rmt$Present the Conservative CHF Composite and house-view rationale.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 3, $rmt$Confirm transfer timing from Privatbank Lindengut (~CHF 10m on signature).$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 4, $rmt$Discuss fee structure and reporting cadence.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 5, $rmt$Agree next steps post tax-adviser review.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 1, $rmt$Confirm investment horizon — discovery suggests 7–10 years.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 2, $rmt$Any liquidity needs in the next 24 months?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 3, $rmt$ESG preferences or exclusions to apply?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002005$rmt$, 4, $rmt$Full CHF 10m at signing, or phased deployment?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002005$rmt$, 1, $rmt$Client narrative brief$rmt$, $rmt$cont_ctsfu45rr71lzzpp5kg7mmd0$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002005$rmt$, 2, $rmt$Custody statement — Privatbank Lindengut (Apr 2026)$rmt$, $rmt$cont_q09qv8xv28kcxz15rk467gp3$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002005$rmt$, 3, $rmt$Client profile$rmt$, $rmt$cont_w7fstb6cx23r94lywkogkm1c$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 1, $rmt$Explain the conservative deployment plan from 100% cash.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 2, $rmt$Define the education liquidity bucket size and placement.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 3, $rmt$Walk through CP-1 model allocation and expected behaviour.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 4, $rmt$Confirm no complex/structured products constraint.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 5, $rmt$Agree implementation timeline (lump-sum vs phased).$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 1, $rmt$Lump-sum deployment or phased entry over 3–6 months?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 2, $rmt$Size of education liquidity bucket (CHF amount)?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 3, $rmt$Any ESG preferences beyond the default?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0002002$rmt$, 4, $rmt$Confirm risk-profiling questionnaire on file.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002002$rmt$, 1, $rmt$Client narrative brief$rmt$, $rmt$cont_dxe926c6uqfqd0omp6spccup$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002002$rmt$, 2, $rmt$Account statement — inherited assets (UBS)$rmt$, $rmt$cont_xfyf29pt9mtbwmzno60nqvtm$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0002002$rmt$, 3, $rmt$Inheritance tax confirmation — Kt. Zürich$rmt$, $rmt$cont_xtw6hn7rtt0d08z0i8n5bj7v$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 1, $rmt$Confirm onboarding document checklist sent.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 2, $rmt$Walk through the agreed strategic asset allocation.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 3, $rmt$Explain the 5% drawdown trigger and de-risking protocol.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 4, $rmt$Tobacco exclusion — note legacy BAT in held-away portfolio.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 5, $rmt$Timeline for funding the USD 10m tranche post-KYC.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 1, $rmt$2019 sale documents from Hollis & Crane — received in full?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 2, $rmt$Trust documentation pack for Ellery Family Settlement?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 3, $rmt$FX conversion timing GBP → USD on funding?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$PTY-0003001$rmt$, 4, $rmt$Future review of ~£24m held-away portfolio?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0003001$rmt$, 1, $rmt$Investment policy statement$rmt$, $rmt$cont_bgrmn6m7lytq8poby4fri14d$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0003001$rmt$, 2, $rmt$Existing portfolio statement$rmt$, $rmt$cont_g1x9kasgobsf0oigr14ehf91$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$PTY-0003001$rmt$, 3, $rmt$CIO house view$rmt$, $rmt$cont_u7d5uu982thrn69aem8xyaiz$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 1, $rmt$Address Lombard coverage warning — Apple-driven breach 22 Jun.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 2, $rmt$Present two education mandate variants (5–8 yr horizon).$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 3, $rmt$ESG vs conventional comparison for balanced profile.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 4, $rmt$Zug property financing — mortgage indicative offer status.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 5, $rmt$Rebalance toward BG-5 model weights.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 1, $rmt$Kaufvertrag and Grundbuchauszug for mortgage offer?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 2, $rmt$Education sub-mandate size and funding source?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 3, $rmt$ESG overlay preference — partial or full?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0049217$rmt$, 4, $rmt$Held-away wealth / share-of-wallet conversation?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PB-0049217$rmt$, 1, $rmt$Client profile$rmt$, $rmt$cont_rx3ol3nanou80e8af2388pt9$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 1, $rmt$Review PE med-tech commitment pipeline — client wants to be consulted.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 2, $rmt$Philanthropy cadence — recent CHF 1.0m grant to Fondation Lavanchy.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 3, $rmt$Succession governance at Lavanchy Patrimoine SA.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 4, $rmt$Alternatives sleeve performance and rebalancing.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 5, $rmt$Lombard facility review outcome.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 1, $rmt$Next PE med-tech commitment — timing and sizing?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 2, $rmt$Succession planning timeline for holding company?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 3, $rmt$Philanthropy grant schedule for H2 2026?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PB-0061884$rmt$, 4, $rmt$Any changes to approved-shelf alternatives list?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PB-0061884$rmt$, 1, $rmt$Client profile$rmt$, $rmt$cont_jx2fkhyfr32gqde96859ht22$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 1, $rmt$Frame the consolidation value proposition vs incumbent.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 2, $rmt$CH/IT cross-border structuring — flag for Compliance.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 3, $rmt$Multi-generational wealth and governance needs.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 4, $rmt$Alternatives and private-markets capabilities.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_talking_points (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 5, $rmt$Relationship model — senior RM continuity.$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 1, $rmt$Tax residence confirmation (CH/IT)?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 2, $rmt$Scope of assets available for transfer?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 3, $rmt$Mandate type preference (discretionary vs advisory)?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_open_questions (client_id, position, text) VALUES ($rmt$CH-PROS-0118$rmt$, 4, $rmt$Timeline and decision process with incumbent providers?$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PROS-0118$rmt$, 1, $rmt$Prospect profile$rmt$, $rmt$cont_ndcyut82lulehqivq3i6nbrp$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
INSERT INTO rm_documents (client_id, position, title, "contentId") VALUES ($rmt$CH-PROS-0118$rmt$, 2, $rmt$Prospect data pack$rmt$, $rmt$cont_d877j32qy16lbf6a639i64b8$rmt$) ON CONFLICT (client_id, position) DO NOTHING;
