[tool.poetry]
name = "tutorials"
version = "0.0.1"
description = ""
authors = ["Cedric Klinkert <cedric@unique.ai>"]
readme = "README.md"
packages = [
    { include = "utilities_examples" },
    { include = "sdk_examples" },
    { include = "toolkit_examples" },
]


[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
unique-toolkit = "^0.7.39"
#unique-toolkit = {git = "https://github.com/Unique-AG/ai/", rev = "84702ff7ab207814156b7b7185fb93dc0443fc47", subdirectory="unique_toolkit"} 

pydantic-settings = "^2.8.1"
aiolimiter = "^1.2.1"
dotenv = "^0.9.9"
httpx = "^0.28.1"
ipykernel = "^6.29.5"
openai = "^1.97.0"
langchain = "^0.3.26"
langchain-openai = "^0.3.28"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.3"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
