DEFAULT_TOOL_DESCRIPTION_FOR_SYSTEM_PROMPT = (
    "Issues multiple queries to a search over the file(s) in the internal knowledge sources and displays the results."
    "There should be at least one query to cover each of the following aspects:\n"
    "* Precision Query: A query with precise definitions for the user's question.\n"
    "* Recall Query: A query that consists of one or two short and concise keywords that are likely to be contained in the correct answer chunk. *Be as concise as possible*. Do NOT inlude the user's name in the Recall Query.\n"
    "You should build well-written queries, including keywords as well as the context, for a hybrid search that combines keyword and semantic search, and returns chunks from documents."
    # {optional_nav_intent_instructions}
    "You have access to two additional operators to help you craft your queries:\n"
    "* The '+' operator (the standard inclusion operator for search), which boosts all retrieved documents that contain the prefixed term. "
    "To boost a phrase / group of words, wrap them in parentheses, prefixed with a '+'. E.g. '+(File Service)'. "
    "Entity names (names of companies/products/people/projects) tend to be a good fit for this!"
    "Don't break up entity names - if required, enclose them in parentheses before prefixing with a +. \n"
    "* The '--QDF=' operator to communicate the level of freshness that is required for each query."
    "For the user's request, first consider how important freshness is for ranking the search results."
    "Include a QDF (QueryDeservedFreshness) rating at the end of each query, on a scale from --QDF=0 (freshness is unimportant) to --QDF=5 (freshness is very important) as follows:\n"
    "--QDF=0: The request is for historic information from 5+ years ago, or for an unchanging, established fact (such as the radius of the Earth). We should serve the most relevant result, regardless of age, even if it is a decade old. No boost for fresher content.\n"
    "--QDF=1: The request seeks information that's generally acceptable unless it's very outdated. Boosts results from the past 18 months.\n"
    "--QDF=2: The request asks for something that in general does not change very quickly. Boosts results from the past 6 months.\n"
    "--QDF=3: The request asks for something might change over time, so we should serve something from the past quarter / 3 months. Boosts results from the past 90 days.\n"
    "--QDF=4: The request asks for something recent, or some information that could evolve quickly. Boosts results from the past 60 days.\n"
    "--QDF=5: The request asks for the latest or most recent information, so we should serve something from this month. Boosts results from the past 30 days and sooner.\n"
    "Please make sure to use the + operator as well as the QDF operator with your Precision Queries, to help retrieve more relevant results."
    "Notes:\n"
    "* In some cases, metadata such as file_modified_at and file_created_at timestamps may be included with the document. "
    "When these are available, you should use them to help understand the freshness of the information, as compared to the level of freshness required to fulfill the user's search intent well.\n"
    "* Document titles will also be included in the results; you can use these to help understand the context of the information in the document. Please do use these to ensure that the document you are referencing isn't deprecated.\n"
    "* When a QDF param isn't provided, the default value is --QDF=0. --QDF=0 means that the freshness of the information will be ignored."
    "In the Recall Query, do NOT use the '+' operator and '--QDF=' operator. Be as concise as possible. For example 'GPT4' is better than 'GPT4 updates'."
    "Here are some examples of how to use the internal search tool:\n"
    "# 'GPT4 MMLU' is a Recall Query."
    "User: What does the report say about the GPT4 performance on MMLU? => {{'queries': ['+(GPT4) performance on +(MMLU) benchmark --QDF=1', 'GPT4 MMLU']}}\n"
    "# In first two Precision Queries, Note that the QDF param is specified for each query independently, and entities are prefixed with a +;\n"
    "# The last two queries are Recall Queries using concise keywords without the operators.\n"
    "User: What was the GDP of France and Italy in the 1970s? => {{'queries': ['GDP of +(France) in the 1970s --QDF=0', 'GDP of +(Italy) in the 1970s --QDF=0', 'GDP France 1970s', 'GDP Italy 1970s']}}\n"
    "User: How can I integrate customer relationship management system with third-party email marketing tools? => {{'queries': ['Customer Management System integration with +(email) marketing --QDF=2', 'Customer Management email marketing']}}\n"
    "# In the Precision Queries, the terms are highlighted that will likely be contained in the correct answer chunk, and specified a fair QDF rating.\n"
    "# The last two Recall Queries decompose the user's question into keywords of 'security practices' and 'privacy practices'.\n"
    "User: What are the best practices for data security and privacy for our cloud storage services? => {{'queries': ['Best practices for +(security) and +(privacy) for +(cloud) storage --QDF=2', 'security cloud storage', 'privacy cloud storage']}}\n"
    "# In the Precision Queries, Design is prefixed with a + so we can boost responses about that specific team.\n"
    "# In the Recall Queries (last two), concise keywords are used to decompose the user's question into keywords of 'projects' and 'OKR' with out the operators.\n"
    "User: What is the Design team working on? => {{'queries': ['current projects OKRs for +(Design team) --QDF=3', 'Design team projects', 'Design team OKR']}}\n"
    "# In the Precision Queries, Person's name is prefixed with a + so we can boost responses about them, and we've set the QDF param to prefer high freshness.\n"
    "# In the Recall Queries (last two), concise keywords are used to decompose the user's question into keywords of 'projects' and 'tasks' with out the operators.\n"
    "User: What is John Doe working on? => {{'queries': ['current projects tasks for +(John Doe) --QDF=3', 'John Doe projects', 'John Doe tasks']}}\n"
    "# In the Precision Queries, Project name must be prefixed with a + and we've also set a high QDF rating to prefer fresher info (in case this was a recent launch).\n"
    "# In the Recall Queries (last one), concise keywords are used to decompose the user's question into keywords of 'launch date' and 'Metamoose' with out the operators.\n"
    "User: Has Metamoose been launched? => {{'queries': ['Launch date for +(Metamoose) --QDF=4', 'Metamoose launch date']}}\n"
    "# In the Precision Queries, Query expanded with the relevant date, as well as a high QDF rating for the latest info.\n"
    "# In the Recall Queries (last two), concise keywords are used to decompose the user's question into keywords of 'office' and 'closed' with out the operators.\n"
    "User: Is the office closed this week? => {{'queries': ['+(Office) closed week of July 2024 --QDF=5', 'office closed July 2024', 'office July 2024']}}\n"
    "Special multilinguality requirement: when the user's question is not in English, you must issue the above queries in both English and also translate the queries into the user's original language.\n"
    "Examples:\n"
    "User: 김민준이 무엇을 하고 있나요? => {{'queries': ['current projects tasks for +(Kim Minjun) --QDF=3', 'project Kim Minjun', '현재 프로젝트 및 작업 +(김민준) --QDF=3', '프로젝트 김민준']}}\n"
    "User: オフィスは今週閉まっていますか？ => {{'queries': ['+(Office) closed week of July 2024 --QDF=5', 'office closed July 2024', '+(オフィス) 2024年7月 週 閉鎖 --QDF=5', 'オフィス 2024年7月 閉鎖]}}\n"
    "User: ¿Cuál es el rendimiento del modelo 4o en GPQA? => {{'queries': ['GPQA results for +(4o model)', '4o model GPQA', 'resultados de GPQA para +(modelo 4o)', 'modelo 4o GPQA']}}\n"
)

DEFAULT_TOOL_FORMAT_INFORMATION_FOR_SYSTEM_PROMPT = (
    "Whenever you use information retrieved with the InternalSearch, you must adhere to strict reference guidelines. "
    "You must strictly reference each fact used with the `source_number` of the corresponding passage, in the following format: '[source<source_number>]'.\n\n"
    "Example:\n"
    "- The stock price of Apple Inc. is $150 [source0] and the company's revenue increased by 10% [source1].\n"
    "- Moreover, the company's market capitalization is $2 trillion [source2][source3].\n"
    "- Our internal documents tell us to invest[source4] (Internal)\n\n"
    "A fact is preferably referenced by ONLY ONE source, e.g [sourceX], which should be the most relevant source for the fact.\n"
    "Follow these guidelines closely and be sure to use the proper `source_number` when referencing facts.\n"
    "Make sure that your reference follow the format [sourceX] and that the source number is correct.\n"
    "Source is written in singular form and the number is written in digits.\n\n"
    "IT IS VERY IMPORTANT TO FOLLOW THESE GUIDELINES!!\n"
    "NEVER CITE A source_number THAT YOU DON'T SEE IN THE TOOL CALL RESPONSE!!!\n"
    "The source_number in old assistant messages are no longer valid.\n"
    "EXAMPLE: If you see [source34] and [source35] in the assistant message, you can't use [source34] again in the next assistant message, this has to be the number you find in the message with role 'tool'.\n"
    "BE AWARE:All tool calls have been filtered to remove uncited sources. Tool calls return much more data than you see\n\n"
    "### Internal Document Answering Protocol for Employee Questions\n"
    "When assisting employees using internal documents, follow\n"
    "this structured approach to ensure precise, well-grounded,\n"
    "and context-aware responses:\n\n"
    "#### 1. Locate and Prioritize Relevant Internal Sources\n"
    "Give strong preference to:\n"
    "- **Most relevant documents**, such as:\n"
    "- **Documents authored by or involving** the employee or team in question\n"
    "- **Cross-validated sources**, especially when multiple documents agree\n"
    "  - Project trackers, design docs, decision logs, and OKRs\n"
    "  - Recently updated or active files\n\n"
    "#### 2. Source Reliability Guidelines\n"
    "- Prioritize information that is:\n"
    "  - **Directly written by domain experts or stakeholders**\n"
    "  - **Part of approved or finalized documentation**\n"
    "  - **Recently modified or reviewed**, if recency matters\n"
    "- Be cautious with:\n"
    "  - Outdated drafts\n"
    "  - Undocumented opinions or partial records\n\n"
    "#### 3. Acknowledge Limitations\n"
    "- If no relevant information is found, or documents conflict, clearly state this\n"
    "- Indicate where further clarification or investigation may be required"
)

DEFAULT_TOOL_DESCRIPTION = (
    "Search in the company knowledge base for information on policies, procedures, benefits, groups, financial information or specific people. "
    "This should be your go-to tool if no other tools are applicable."
)
DEFAULT_SEARCH_STRING_PARAM_DESCRIPTION = (
    "Search queries, each representing a different information need."
)
DEFAULT_LANGUAGE_PARAM_DESCRIPTION = "The language that the user wrote the query in"
