[tool.poetry]
name = "unique_stock_ticker"
version = "0.0.1"
description = ""
authors = [
    "Martin Fadler <martin.fadler@unique.ch>",
    "Sadique Sheik <sadique@unique.ch>",
    "Fabian Schläpfer <fabian@unique.ch>",
    "Pascal Hauri <pascal@unique.ch>",
]
readme = ["README.md", "CHANGELOG.md"]
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.11"
typing-extensions = "^4.9.0"
pydantic = "^2.8.2"
pydantic-settings = "^2.10.1"
python-dotenv = "^1.0.1"
unique-sdk = "^0.10.0"
unique-toolkit = "^0.8.12"
plotly = "^6.3.0"
numerize = "^0.12"
pytest = "^8.4.1"


[tool.poetry.group.dev.dependencies]
python = "^3.11"
typing-extensions = "^4.9.0"
pydantic = "^2.8.2"
pydantic-settings = "^2.10.1"
unique-sdk = { path = "../unique_sdk" }
unique-toolkit = { path = "../unique_toolkit" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = ["I"]
