name: 'Select Packages'
description: 'Filters package list based on workflow_dispatch input or path changes'

inputs:
  packages:
    description: 'JSON array of package configurations (each must have an "id" field)'
    required: true
  selected:
    description: 'Selected package from workflow_dispatch (empty for auto-detect, "all" for all)'
    required: false
    default: ''
  changes:
    description: 'JSON object from paths-filter outputs'
    required: true

outputs:
  matrix:
    description: 'Matrix JSON for use with strategy.matrix'
    value: ${{ steps.build.outputs.matrix }}

runs:
  using: 'composite'
  steps:
    - name: Build matrix
      id: build
      shell: bash
      run: |
        PACKAGES='${{ inputs.packages }}'
        SELECTED="${{ inputs.selected }}"
        CHANGES='${{ inputs.changes }}'

        if [ "$SELECTED" = "all" ]; then
          MATRIX="$PACKAGES"
        elif [ -n "$SELECTED" ]; then
          # Filter by selected package id
          MATRIX=$(echo "$PACKAGES" | jq -c --arg id "$SELECTED" '[.[] | select(.id == $id)]')
        else
          # Auto-detect: filter packages where the corresponding path changed
          MATRIX=$(echo "$PACKAGES" | jq -c --argjson changes "$CHANGES" '
            [.[] | select($changes[.id] == "true")]
          ')
        fi

        echo "matrix={\"include\":$MATRIX}" >> $GITHUB_OUTPUT
        echo "Generated matrix: $MATRIX"
