from enum import StrEnum


class MicType(StrEnum):
    OPERATING = "OPERATING"
    SEGMENT = "SEGMENT"
    OTHER = "OTHER"


class MarketType(StrEnum):
    TRADING_PLACE_MARKET = "TRADING_PLACE_MARKET"
    NEWS_AGENCY = "NEWS_AGENCY"
    DIRECT_PRICE_INFORMATION_PROVIDER_CONTRIBUTOR = (
        "DIRECT_PRICE_INFORMATION_PROVIDER_CONTRIBUTOR"
    )
    INDIRECT_PRICE_INFORMATION_PROVIDER = "INDIRECT_PRICE_INFORMATION_PROVIDER"
    SIX_MANAGED_PRICE_INFORMATION = "SIX_MANAGED_PRICE_INFORMATION"
    OTHER = "OTHER"


class MarketStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    REFERENCE_ONLY = "REFERENCE_ONLY"
    OTHER = "OTHER"
