-- SQLite schema and seed data for pm_positions (in-memory demo DB)
CREATE TABLE IF NOT EXISTS pm_positions (
  row_num       INTEGER PRIMARY KEY,
  sleeve        TEXT NOT NULL,
  ticker        TEXT NOT NULL,
  instrument    TEXT NOT NULL,
  direction     TEXT NOT NULL,
  target_weight REAL NOT NULL,
  position_mm   INTEGER NOT NULL,
  email         TEXT
);

-- Seed data. INSERT OR IGNORE skips rows that would violate the primary key (row_num),
-- so this script can be run multiple times without errors (idempotent).
INSERT OR IGNORE INTO pm_positions (row_num, sleeve, ticker, instrument, direction, target_weight, position_mm, email) VALUES
(1, 'Equity Long', 'MSFT', 'Microsoft', 'Long', 0.05, 100, 'alice@alphabet.example'),
(2, 'Equity Long', 'JNJ', 'Johnson & Johnson', 'Long', 0.04, 80, 'alice@alphabet.example'),
(3, 'Equity Long', 'UNH', 'UnitedHealth', 'Long', 0.035, 70, 'alice@alphabet.example'),
(4, 'Equity Beta', 'SPY', 'S&P 500 ETF', 'Long', 0.15, 300, 'tin.oroz@unique-ai-academy.com'),
(5, 'Equity Long', 'AAPL', 'Apple Inc', 'Long', 0.08, 160, 'tin.oroz@unique-ai-academy.com'),
(6, 'Equity Long', 'NVDA', 'NVIDIA', 'Long', 0.06, 120, 'tin.oroz@unique-ai-academy.com'),
(7, 'Equity Short', 'QQQ', 'Nasdaq-100 ETF', 'Short', -0.04, -80, 'tin.oroz@unique-ai-academy.com'),
(8, 'Rates', 'TLT', '20+ Year Treasury Bond', 'Long', 0.10, 200, 'tin.oroz@unique-ai-academy.com'),
(9, 'Alternatives', 'GLD', 'Gold', 'Long', 0.05, 100, 'tin.oroz@unique-ai-academy.com'),
(10, 'Equity Beta', 'VOO', 'Vanguard S&P 500 ETF', 'Long', 0.08, 160, 'tin.oroz@unique-ai-academy.com'),
(11, 'Equity Long', 'ALV', 'Allianz SE', 'Long', 0.0496, 496, 'marcluginbuehl@metzler.com'),
(12, 'Equity Long', 'BAS', 'BASF SE', 'Long', 0.0071, 72, 'marcluginbuehl@metzler.com'),
(13, 'Equity Long', 'BAYN', 'Bayer AG', 'Long', 0.0047, 47, 'marcluginbuehl@metzler.com'),
(14, 'Equity Long', 'BMW', 'BMW AG', 'Long', 0.0074, 74, 'marcluginbuehl@metzler.com'),
(15, 'Equity Long', 'MBG', 'Mercedes-Benz Group AG', 'Long', 0.0137, 138, 'marcluginbuehl@metzler.com'),
(16, 'Equity Long', 'VOW3', 'Volkswagen AG', 'Long', 0.0231, 231, 'marcluginbuehl@metzler.com'),
(17, 'Equity Long', 'SIE', 'Siemens AG', 'Long', 0.0672, 672, 'marcluginbuehl@metzler.com'),
(18, 'Equity Long', 'DTE', 'Deutsche Telekom AG', 'Long', 0.0278, 278, 'marcluginbuehl@metzler.com'),
(19, 'Equity Long', 'MUV2', 'Münchener Rück', 'Long', 0.0279, 280, 'marcluginbuehl@metzler.com'),
(20, 'Equity Long', 'HNR1', 'Hannover Rück', 'Long', 0.0123, 123, 'marcluginbuehl@metzler.com'),
(21, 'Equity Long', 'DHL', 'Deutsche Post AG', 'Long', 0.0189, 189, 'marcluginbuehl@metzler.com'),
(22, 'Equity Long', 'EOAN', 'E.ON SE', 'Long', 0.0398, 398, 'marcluginbuehl@metzler.com'),
(23, 'Equity Long', 'RWE', 'RWE AG', 'Long', 0.0023, 23, 'marcluginbuehl@metzler.com'),
(24, 'Equity Long', 'SAP', 'SAP SE', 'Long', 0.0108, 108, 'marcluginbuehl@metzler.com'),
(25, 'Equity Long', 'FRE', 'Fresenius SE', 'Long', 0.0281, 281, 'marcluginbuehl@metzler.com'),
(26, 'Equity Long', 'FME', 'Fresenius Medical Care', 'Long', 0.0015, 15, 'marcluginbuehl@metzler.com'),
(27, 'Equity Long', 'HEI', 'Heidelberg Materials', 'Long', 0.006, 60, 'marcluginbuehl@metzler.com'),
(28, 'Equity Long', 'HEN3', 'Henkel AG', 'Long', 0.0039, 39, 'marcluginbuehl@metzler.com'),
(29, 'Equity Long', 'BEI', 'Beiersdorf AG', 'Long', 0.0132, 132, 'marcluginbuehl@metzler.com'),
(30, 'Equity Long', 'CON', 'Continental AG', 'Long', 0.0071, 71, 'marcluginbuehl@metzler.com'),
(31, 'Equity Long', 'PAH3', 'Porsche Automobil Holding', 'Long', 0.0117, 117, 'marcluginbuehl@metzler.com'),
(32, 'Equity Long', 'SY1', 'Symrise AG', 'Long', 0.0282, 282, 'marcluginbuehl@metzler.com'),
(33, 'Equity Long', '1COV', 'Covestro AG', 'Long', 0.0261, 261, 'marcluginbuehl@metzler.com'),
(34, 'Equity Long', 'LXS', 'LANXESS AG', 'Long', 0.0095, 95, 'marcluginbuehl@metzler.com'),
(35, 'Equity Long', 'LEG', 'LEG Immobilien', 'Long', 0.0044, 44, 'marcluginbuehl@metzler.com'),
(36, 'Equity Long', 'VNA', 'Vonovia SE', 'Long', 0.0211, 212, 'marcluginbuehl@metzler.com'),
(37, 'Equity Long', 'SHL', 'Siemens Healthineers', 'Long', 0.006, 60, 'marcluginbuehl@metzler.com'),
(38, 'Equity Long', 'ENR', 'Siemens Energy', 'Long', 0.0067, 67, 'marcluginbuehl@metzler.com'),
(39, 'Equity Long', 'MTX', 'MTU Aero Engines', 'Long', 0.0116, 116, 'marcluginbuehl@metzler.com'),
(40, 'Equity Long', 'NDA', 'Aurubis AG', 'Long', 0.0672, 673, 'marcluginbuehl@metzler.com'),
(41, 'Equity Long', 'SDF', 'K+S AG', 'Long', 0.0509, 509, 'marcluginbuehl@metzler.com'),
(42, 'Equity Long', 'PUM', 'Puma SE', 'Long', 0.0725, 726, 'marcluginbuehl@metzler.com'),
(43, 'Equity Long', 'ZAL', 'Zalando SE', 'Long', 0.0261, 261, 'marcluginbuehl@metzler.com'),
(44, 'Equity Long', 'HFG', 'HelloFresh SE', 'Long', 0.0068, 68, 'marcluginbuehl@metzler.com'),
(45, 'Equity Long', 'DB1', 'Deutsche Börse AG', 'Long', 0.0385, 386, 'marcluginbuehl@metzler.com'),
(46, 'Equity Long', 'CBK', 'Commerzbank AG', 'Long', 0.0222, 223, 'marcluginbuehl@metzler.com'),
(47, 'Equity Long', 'ARL', 'Aareal Bank', 'Long', 0.0072, 72, 'marcluginbuehl@metzler.com'),
(48, 'Equity Long', 'FPE3', 'Fuchs Petrolub', 'Long', 0.0227, 228, 'marcluginbuehl@metzler.com'),
(49, 'Equity Long', 'RRTL', 'RTL Group', 'Long', 0.0099, 99, 'marcluginbuehl@metzler.com'),
(50, 'Equity Long', 'HOT', 'Hochtief AG', 'Long', 0.0262, 262, 'marcluginbuehl@metzler.com'),
(51, 'Equity Long', 'GBF', 'Bilfinger SE', 'Long', 0.0256, 257, 'marcluginbuehl@metzler.com'),
(52, 'Equity Long', 'WCH', 'Wacker Chemie', 'Long', 0.0069, 69, 'marcluginbuehl@metzler.com'),
(53, 'Equity Long', 'GXI', 'Gerresheimer AG', 'Long', 0.0636, 636, 'marcluginbuehl@metzler.com'),
(54, 'Equity Long', 'G1A', 'GEA Group', 'Long', 0.0336, 336, 'marcluginbuehl@metzler.com'),
(55, 'Equity Long', 'TLX', 'Talanx AG', 'Long', 0.0224, 224, 'marcluginbuehl@metzler.com'),
(56, 'Equity Alpha', 'SPY', 'S&P 500 ETF', 'Long', 0.10, 200, 'tinoroz@metzler.com'),
(57, 'Equity Beta', 'SPY', 'S&P 500 ETF', 'Long', 0.05, 100, 'tinoroz@metzler.com'),
(58, 'Equity Beta', 'SPY', 'S&P 500 ETF', 'Long', 0.08, 160, 'tinoroz@metzler.com');
