from enum import Enum


class BraveSearchRequestCountryType0(str, Enum):
    ALL = "ALL"
    AR = "AR"
    AT = "AT"
    AU = "AU"
    BE = "BE"
    BR = "BR"
    CA = "CA"
    CH = "CH"
    CL = "CL"
    CN = "CN"
    DE = "DE"
    DK = "DK"
    ES = "ES"
    FI = "FI"
    FR = "FR"
    GB = "GB"
    GR = "GR"
    HK = "HK"
    ID = "ID"
    IN = "IN"
    IT = "IT"
    JP = "JP"
    KR = "KR"
    MX = "MX"
    MY = "MY"
    NL = "NL"
    NO = "NO"
    NZ = "NZ"
    PH = "PH"
    PL = "PL"
    PT = "PT"
    RU = "RU"
    SA = "SA"
    SE = "SE"
    TR = "TR"
    TW = "TW"
    US = "US"
    ZA = "ZA"

    def __str__(self) -> str:
        return str(self.value)
