from enum import Enum


class BraveSearchRequestUILanguage(str, Enum):
    DA_DK = "da-DK"
    DE_AT = "de-AT"
    DE_CH = "de-CH"
    DE_DE = "de-DE"
    EL_GR = "el-GR"
    EN_AU = "en-AU"
    EN_CA = "en-CA"
    EN_GB = "en-GB"
    EN_ID = "en-ID"
    EN_IN = "en-IN"
    EN_MY = "en-MY"
    EN_NZ = "en-NZ"
    EN_PH = "en-PH"
    EN_US = "en-US"
    EN_ZA = "en-ZA"
    ES_AR = "es-AR"
    ES_CL = "es-CL"
    ES_ES = "es-ES"
    ES_MX = "es-MX"
    ES_US = "es-US"
    FI_FI = "fi-FI"
    FR_BE = "fr-BE"
    FR_CA = "fr-CA"
    FR_CH = "fr-CH"
    FR_FR = "fr-FR"
    IT_IT = "it-IT"
    JA_JP = "ja-JP"
    KO_KR = "ko-KR"
    NL_BE = "nl-BE"
    NL_NL = "nl-NL"
    NO_NO = "no-NO"
    PL_PL = "pl-PL"
    PT_BR = "pt-BR"
    RU_RU = "ru-RU"
    SV_SE = "sv-SE"
    TR_TR = "tr-TR"
    ZH_CN = "zh-CN"
    ZH_HK = "zh-HK"
    ZH_TW = "zh-TW"

    def __str__(self) -> str:
        return str(self.value)
