from enum import Enum


class BraveSearchRequestSearchLangType0(str, Enum):
    AR = "ar"
    BG = "bg"
    BN = "bn"
    CA = "ca"
    CS = "cs"
    DA = "da"
    DE = "de"
    EL = "el"
    EN = "en"
    EN_GB = "en-gb"
    ES = "es"
    ET = "et"
    EU = "eu"
    FI = "fi"
    FR = "fr"
    GL = "gl"
    GU = "gu"
    HE = "he"
    HI = "hi"
    HR = "hr"
    HU = "hu"
    IS = "is"
    IT = "it"
    JP = "jp"
    KN = "kn"
    KO = "ko"
    LT = "lt"
    LV = "lv"
    ML = "ml"
    MR = "mr"
    MS = "ms"
    NB = "nb"
    NL = "nl"
    PA = "pa"
    PL = "pl"
    PT_BR = "pt-br"
    PT_PT = "pt-pt"
    RO = "ro"
    RU = "ru"
    SK = "sk"
    SL = "sl"
    SR = "sr"
    SV = "sv"
    TA = "ta"
    TE = "te"
    TH = "th"
    TR = "tr"
    UK = "uk"
    VI = "vi"
    ZH_HANS = "zh-hans"
    ZH_HANT = "zh-hant"

    def __str__(self) -> str:
        return str(self.value)
