site_name: Unique Toolkit

nav:
  - Home: index.md
  - Environment Setup: ./setup/getting_started.md
  - Tutorials: 
    - ./application_types/standalone_application.md
    - ./application_types/event_driven_applications.md
    - ./modules/examples/chat/chat_service.md
    - ./modules/examples/content/content_service.md
    - ./plattforms/openai/openai.md
  - API Reference: api.md
  - Readme: readme.md 