site_name: Unique Toolkit
site_description: Documentation for the Unique Toolkit
site_author: Unique Team

theme:
  name: material
  highlithjs: true
  jljs_languages:
    - python

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tutorials: 
    - tutorials.md
    - ./plattforms/openai/openai.md
  - API Reference: api.md
  - Readme: readme.md
  - Changelog: CHANGELOG.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde

docs_dir: docs
site_dir: site

plugins:
  - search
  - include-markdown 
  - callouts
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            show_root_heading: true
            show_source: true
            filters:
              - "!.[company|user|assistant|chat|assistant_id|assistant_message_id|user_message_id]_id.*"
              - "!.*_async.*"
              - "!.*event.*"
            extra:
              show_signature_annotations: true
              show_type_annotations: true
              show_if_no_docstring: false