name: 'Run Tests'
description: 'Runs pytest tests, supporting both Poetry and uv'

inputs:
  package_dir:
    description: 'Path to the package directory'
    required: true
  package_manager:
    description: 'Package manager to use: auto (detect), poetry, or uv'
    required: false
    default: 'auto'
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  package_manager_version:
    description: 'Package manager version to install (e.g., "1.8.3" for Poetry, ignored for uv)'
    required: false
    default: '1.8.3'
  test_args:
    description: 'Additional arguments to pass to pytest'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install package manager
      id: install_pm
      uses: ./.github/actions/install-package-manager
      with:
        package_dir: ${{ inputs.package_dir }}
        package_manager: ${{ inputs.package_manager }}
        python_version: ${{ inputs.python_version }}
        package_manager_version: ${{ inputs.package_manager_version }}

    - name: Run pytest
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: |
        ${{ steps.install_pm.outputs.run_cmd }} pytest ${{ inputs.test_args }}

