# tool_prompts.py — GENERATED by python/rm-demo/src/generate_tool_prompts.py
# from resources/unique/MCP_SERVERS.md. DO NOT EDIT BY HAND — edit the MD and re-run.
#
"""Per-tool Unique AI prompt metadata for the `RM Agent - CRM` connector.

Unique reads these two keys off each MCP tool's ``_meta`` and renders them as the
tool's "System Prompt: Tool Usage Instructions" and "System Prompt: Tool Response
Format Instructions" (unique_mcp MetaKeys: UNIQUE_AI_TOOL_SYSTEM_PROMPT /
UNIQUE_AI_TOOL_FORMAT_INFORMATION). Attach them via :func:`tool_meta`.
"""

SYSTEM_PROMPT_META_KEY = "unique.app/system-prompt"
FORMAT_INFO_META_KEY = "unique.app/tool-format-information"

TOOL_PROMPTS = {
    "delete_document": {
        "system_prompt": "WRITE (one document). Input: `client_id` (or `input`) + `position`. Removes a document from the dashboard's Facility Documents.",
        "format": "Deletes the matching row (`{client_id, position, deleted:true}`).",
    },
    "delete_open_question": {
        "system_prompt": "WRITE (one question). Input: `client_id` (or `input`) + `position`. Removes that open question.",
        "format": "Deletes the matching row (`{client_id, position, deleted:true}`).",
    },
    "delete_talking_point": {
        "system_prompt": "WRITE (one point). Input: `client_id` (or `input`) + `position`. Removes that talking point. Call `get_talking_points` first to find the position.",
        "format": "Deletes the matching row (`{client_id, position, deleted:true}`); the dashboard drops it on refresh.",
    },
    "edit_dashboard_section": {
        "system_prompt": "WRITE (whole card, server-side). Input: `client_id`; `action` (`list` | `remove` | `add`); `section` (a key — `recommendation` / `house_view` / `model_portfolio` / `talking_points` / `open_questions` / `facility_documents` — or a card id like `mod-5`; omit for `list`); and `content_id` (the dashboard's `cont_…` id — it's in the Edit-with-AI prompt; pass it so the exact file is edited). Make ONE call — it toggles the card and saves the file with the server's own credentials. Do NOT download / edit / `unique-cli upload` the dashboard (the agent's task scope is read-only on that document). If it returns \"MCP tool is not enabled\", stop and tell the RM the tool needs enabling/re-syncing on this connector — do not fall back to the CLI.",
        "format": "`list` → `{client_id, present:[{id,key}], addable:[{id,key}]}`. `remove`/`add` → `{client_id, section, id, action, changed:true, note}` (or `changed:false` with a `note` — e.g. \"already removed\" / \"already present\"). On success tell the RM to **Refresh** the dashboard.",
    },
    "get_entity_ownership": {
        "system_prompt": "Input: a client name or client_id. Use to understand the legal-entity / ownership (UBO) structure.",
        "format": "Returns `{client_id, entity_type, beneficial_owners[], directors[], controllers[], authorised_signatories[], ownership_structure_depth, note}`. For individuals these arrays are empty (the note says so). An empty UBO list on a wired entity means 'to be verified', not 'none'.",
    },
    "get_history": {
        "system_prompt": "Input: a client name or client_id. Use to prep for a meeting or summarise the relationship.",
        "format": "Returns `{client_id, interaction_log[], open_tasks[{task,due,status}], life_events[], complaints[]}`. Lead with the most recent interactions and any overdue/open tasks.",
    },
    "get_identifiers": {
        "system_prompt": "Input: a client name or client_id. Use for KYC / onboarding identifier lookups.",
        "format": "Returns `{client_id, passport, national_id, lei, company_registration, internal_party_id}` (only the applicable fields are present). Do not expose full document numbers unless the task requires it.",
    },
    "get_mandate_objectives": {
        "system_prompt": "Input: a client name or client_id. Use to anchor any advice to the client's mandate.",
        "format": "Returns `{client_id, mandate_type, investment_objective, risk_profile, investment_horizon_liquidity, constraints_exclusions[], reference_currency, fee_schedule?}`. Treat `risk_profile`, `constraints_exclusions`, and `reference_currency` as binding. Null fields ⇒ not yet captured (prospect).",
    },
    "get_meetings": {
        "system_prompt": "Input: a client name/id, an RM username (e.g. marc.dubois), 'week', or omit for all upcoming. Resolve client names the same way as the identity tools.",
        "format": "Returns `{count, meetings:[{...,start/start_at,title,type,client,client_id,rm,channel,agenda,status}], client_id?}`, sorted by start time. Lead with the soonest relevant meeting; present times in the event's timezone.",
    },
    "get_next_meeting": {
        "system_prompt": "Input: a client name or client_id. A named client that doesn't resolve returns an `Unknown client` hint (not the global next meeting).",
        "format": "Returns `{next_meeting:{...}|null, client_id?}`. If `next_meeting` is null there is nothing upcoming for that client.",
    },
    "get_open_questions": {
        "system_prompt": "Input: `client_id` (or `input`). Reads the client's OPEN QUESTIONS — the live list shown on the dashboard. Change with `upsert_open_question` / `delete_open_question`.",
        "format": "Returns a top-level array of rows (each `{client_id, position, text}`), listed by `position`.",
    },
    "get_party_identity": {
        "system_prompt": "Resolve a client by name or client_id and confirm their legal identity. Input: `{\"input\":\"<name or client_id>\"}`. Call this first to make sure you have the right party.",
        "format": "Returns `{client_id, full_legal_name, aliases, date_of_birth, place_of_birth, gender, nationalities[], country_of_residence, tax_residences[]}`. Lead with legal name + DOB + nationalities; surface tax residence for cross-border context.",
    },
    "get_relationship": {
        "system_prompt": "Input: a client name or client_id. Use for relationship context and routing.",
        "format": "Returns `{client_id, client_vs_prospect, owning_rm_team_booking_centre{rm,team,booking_centre}, client_segment, referral_source, languages[], contact{...}}`. Use status (client vs prospect), segment, and owning RM to set tone and routing.",
    },
    "get_talking_points": {
        "system_prompt": "Input: `client_id` (or `input`) — a client name or id. Reads the client's meeting TALKING POINTS — the live list shown on the investment-proposal dashboard. Each row is one point. Change with `upsert_talking_point` / `delete_talking_point`.",
        "format": "Returns a top-level array of rows (each `{client_id, position, text}`), which the dashboard lists by `position`.",
    },
    "list_available_documents": {
        "system_prompt": "Input: a client name or client_id. Returns the full CATALOG of documents in that client's KB folder, each with its contentId — the candidate set for the dashboard's Facility Documents. Use it when curating that list: read the catalog, pick the contentIds the RM wants, then add them with `upsert_document` (same connector).",
        "format": "Returns `{client_id, count, documents:[{title, contentId, kind}], items}` where `title` is a readable form of the filename.",
    },
    "list_clients": {
        "system_prompt": "Roster + search. `{}` (no args) → the whole book; or search/filter with `q` (free-text over name/id/segment/rm/status), `status` (client|prospect), `segment`, `rm`, and `limit`/`skip` for pagination — e.g. `{\"q\":\"Brunner\"}`, `{\"segment\":\"UHNW\"}`. Use to find clients at scale (the chat search) and to populate the cockpit.",
        "format": "Returns `{total, count, skip, limit, clients:[{client_id, name, status, segment, rm, value_label, model, dashboard_path, content_id, open_doc_payload, …}]}`. `total` = full matches, `count` = returned this page. Each row carries the path + contentId to that client's pregenerated dashboard; render as a roster, not prose.",
    },
    "list_documents": {
        "system_prompt": "Input: `client_id` (or `input`). Returns the FACILITY DOCUMENTS shown on the proposal dashboard. Change with `upsert_document` / `delete_document`. (To discover candidate files + contentIds, use `list_available_documents`.)",
        "format": "Returns a top-level array of rows (each `{client_id, position, title, contentId, open_doc_payload}`), listed by `position`. `open_doc_payload` is a `{\"contentId\":\"cont_…\"}` JSON string the dashboard's Open button attr-binds for openDocument (same pattern as list_clients.open_doc_payload).",
    },
    "Reset_Demo_Data": {
        "system_prompt": "No input. Operator/demo tool only — call BETWEEN demo runs to restore the baseline (including the editable client memory). Never call it as part of answering a client question.",
        "format": "Returns `{reset:true, tables:{...row counts...}, total_rows, note}`. Confirm the reset succeeded; do not surface to the client.",
    },
    "upsert_document": {
        "system_prompt": "WRITE (one document). Input: `client_id` (or `input`), `position`, `title`, `contentId` (a valid `cont_…` from `list_available_documents`). Adds a document to the dashboard's Facility Documents at a new position, or changes one at an existing position.",
        "format": "Upserts the row `{client_id, position, updated:true, title, contentId}`; the dashboard shows it on refresh.",
    },
    "upsert_open_question": {
        "system_prompt": "WRITE (one question). Input: `client_id` (or `input`), `position` (next free number to add, or an existing one to change), `text` (≤200 chars). Matches on client_id + position; read first with `get_open_questions`. Keep ≤20 per client.",
        "format": "Upserts the row and echoes the stored `{client_id, position, updated:true, text}`; the dashboard shows it on refresh.",
    },
    "upsert_talking_point": {
        "system_prompt": "WRITE (one point). Input: `client_id` (or `input`), `position` (the slot — next free number to ADD, or an existing number to CHANGE), `text` (≤200 chars). Matches on client_id + position. Call `get_talking_points` first to see current positions. Keep ≤20 points per client.",
        "format": "Upserts the row (insert if the position is new, else update) and echoes the stored `{client_id, position, updated:true, text}`. The dashboard shows it on refresh.",
    },
}


def tool_meta(name, base=None):
    """Merge a tool's existing meta (e.g. its icon) with its Usage / Response-Format
    system-prompt metadata so Unique AI shows them as the tool's instructions.
    Returns the merged dict, or None when there is nothing to attach."""
    meta = dict(base or {})
    prompts = TOOL_PROMPTS.get(name)
    if prompts:
        if prompts.get("system_prompt"):
            meta[SYSTEM_PROMPT_META_KEY] = prompts["system_prompt"]
        if prompts.get("format"):
            meta[FORMAT_INFO_META_KEY] = prompts["format"]
    return meta or None
