# %%
# Code execution with custom Azure container (Responses API)
from unique_toolkit.framework_utilities.openai.client import get_openai_client
from unique_toolkit.language_model import LanguageModelName

model_name = LanguageModelName.AZURE_GPT_5_2025_0807

client = get_openai_client(additional_headers={"x-model": model_name})

# %%
# Create a custom Azure container
# Recommended to use chat_id in the name to differentiate containers across chats

container = client.containers.create(
    name="code_execution_container",
    expires_after={"anchor": "last_active_at", "minutes": 20},
)
print(f"Created container: {container.id}")

# %%
# Upload a file to the container

csv_bytes = b"name,value\nfoo,1\nbar,2"
uploaded_file = client.containers.files.create(
    container.id,
    file=("data.csv", csv_bytes),
)
print(f"Uploaded file: {uploaded_file.id}")

# %%
# Download a file from the container
# Files produced by code execution are accessible the same way via file_id

file_id = uploaded_file.id  # or any file_id from a code interpreter output
file_content = client.containers.files.content.retrieve(
    file_id,
    container_id=container.id,
)
downloaded_bytes = file_content.read()
assert downloaded_bytes == csv_bytes

# %%
# List all files in the container

for file in client.containers.files.list(container.id):
    print(f"  {file.id}  {file.path}")

# %%
# Define tools and call Responses API

from openai.types.responses.tool_param import CodeInterpreter

code_interpreter_tool = CodeInterpreter(type="code_interpreter", container=container.id)
messages = "Read data.csv and add a random column. Save the result to a new file called data_with_random_column.csv."

response_with_output = client.responses.create(
    model=model_name,
    tools=[code_interpreter_tool],
    input=messages,
    include=["code_interpreter_call.outputs"],
)

# %%
# Download a file generated by the model during code execution
# File citations appear as annotations on output text items

from openai.types.responses import ResponseOutputMessage

generated_file_id = None
for item in response_with_output.output:
    if isinstance(item, ResponseOutputMessage):
        for content in item.content:
            if content.type == "output_text":
                for annotation in content.annotations:
                    if annotation.type == "container_file_citation":
                        generated_file_id = annotation.file_id
                        print(f"Generated file: {annotation.filename}  ({generated_file_id})")

# %%
if generated_file_id:
    generated_content = client.containers.files.content.retrieve(
        generated_file_id,
        container_id=container.id,
    )
    generated_bytes = generated_content.read()
    print(f"Downloaded generated file: {len(generated_bytes)} bytes")
    print(generated_bytes)

# %%
# Check if a container exists and is usable before reusing it
# Useful when storing container.id across sessions (e.g. in chat state)

from openai import NotFoundError

stored_container_id = container.id  # e.g. loaded from persistent state

try:
    existing_container = client.containers.retrieve(stored_container_id)
    if existing_container.status not in ["active", "running"]:
        container = client.containers.create(
            name="code_execution_container",
            expires_after={"anchor": "last_active_at", "minutes": 20},
        )
    else:
        container = existing_container
except NotFoundError:
    container = client.containers.create(
        name="code_execution_container",
        expires_after={"anchor": "last_active_at", "minutes": 20},
    )

# %%
# Check if a file already exists in the container before re-uploading

stored_file_id = uploaded_file.id  # e.g. loaded from persistent state

try:
    client.containers.files.retrieve(stored_file_id, container_id=container.id)
    print("File already exists, skipping upload")
except NotFoundError:
    uploaded_file = client.containers.files.create(
        container.id,
        file=("data.csv", csv_bytes),
    )
    print(f"Re-uploaded file: {uploaded_file.id}")
