from enum import StrEnum


class ListingIdentifierScheme(StrEnum):
    ISIN_BC = "ISIN_BC"
    VALOR_BC = "VALOR_BC"
    SEDOL_BC = "SEDOL_BC"
    CUSIP_BC = "CUSIP_BC"
    TICKER_BC = "TICKER_BC"
    CINS_BC = "CINS_BC"
    COMMONCODE_BC = "COMMONCODE_BC"
    WKN_BC = "WKN_BC"


class ListingStatus(StrEnum):
    UNOFFICIALLY_LISTED_ACCORDING_TO_EXCHANGE = (
        "UNOFFICIALLY_LISTED_ACCORDING_TO_EXCHANGE"
    )
    APPLIED = "APPLIED"
    LISTED = "LISTED"
    SUSPENDED = "SUSPENDED"
    WITHDRAWN = "WITHDRAWN"
    DELISTED_BY_EXCHANGE = "DELISTED_BY_EXCHANGE"
    PROVISIONAL = "PROVISIONAL"
    WHEN_ISSUED = "WHEN_ISSUED"
    NOT_LISTED = "NOT_LISTED"
    ADMITTED_TO_TRADING = "ADMITTED_TO_TRADING"
    OFFICIAL_LISTING_ACC_TO_REGULATORY_AUTHORITY = (
        "OFFICIAL_LISTING_ACC_TO_REGULATORY_AUTHORITY"
    )
    VIRTUAL_LISTING_DERIVED_VALUES_ONLY = "VIRTUAL_LISTING_DERIVED_VALUES_ONLY"
    LISTING_NO_TRADING = "LISTING_NO_TRADING"
    OTHER = "OTHER"
