from enum import StrEnum


class SecurityType(StrEnum):
    DEBT = "DEBT"
    EQUITY = "EQUITY"
    INVESTMENT_TRUST_UNIT_SHARE = "INVESTMENT_TRUST_UNIT_SHARE"
    ETD = "ETD"
    LEVERAGED_PRODUCT_SUBSCRIPTION_RIGHT = "LEVERAGED_PRODUCT_SUBSCRIPTION_RIGHT"
    CURRENCY = "CURRENCY"
    INDEX = "INDEX"
    INTEREST_RATE = "INTEREST_RATE"
    COMMODITY = "COMMODITY"
    STRUCTURED_PRODUCT = "STRUCTURED_PRODUCT"
    ETD_CONTRACT_SPECIFICATION = "ETD_CONTRACT_SPECIFICATION"
    OTHER = "OTHER"
