name: 'Run Min Tests and Deptry'
description: 'Runs deptry on all packages, and min-deps pytest tests for uv packages only'

inputs:
  package_dir:
    description: 'Path to the package directory'
    required: true
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  test_args:
    description: 'Additional arguments to pass to pytest'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install package manager
      id: pm
      uses: ./.github/actions/install-package-manager
      with:
        package_dir: ${{ inputs.package_dir }}
        python_version: ${{ inputs.python_version }}

    # uv: Install with min deps
    - name: Install package (min deps - uv)
      if: steps.pm.outputs.run_cmd == 'uv run'
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: |
        uv venv --clear
        uv pip install -e . --resolution=lowest-direct
        uv export --only-group dev --no-hashes | uv pip install -r -

    # Poetry: Normal install (deptry is in dev dependencies)
    - name: Install package (poetry)
      if: steps.pm.outputs.run_cmd == 'poetry run'
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: poetry install

    - name: Run deptry (uv)
      if: steps.pm.outputs.run_cmd == 'uv run'
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: uv run --no-sync deptry .

    - name: Run deptry (poetry)
      if: steps.pm.outputs.run_cmd == 'poetry run'
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: poetry run deptry .

    - name: Run tests with min dependencies (uv only)
      if: steps.pm.outputs.run_cmd == 'uv run'
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: uv run --no-sync pytest ${{ inputs.test_args }}
