name: 'Run Min Tests and Deptry'
description: 'Runs pytest tests with min dependencies and deptry, supporting only uv'

inputs:
  package_dir:
    description: 'Path to the package directory'
    required: true
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  test_args:
    description: 'Additional arguments to pass to pytest'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install package manager
      id: install_pm
      uses: ./.github/actions/install-package-manager
      with:
        package_dir: ${{ inputs.package_dir }}
        package_manager: uv
        python_version: ${{ inputs.python_version }}

    - name: Install package (min)
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: |
        uv venv
        # Install runtime deps at minimum versions
        uv pip install -e . --resolution=lowest-direct
        # Install dev deps from [dependency-groups] (we only care about runtime dep minimums)
        uv export --only-group dev --no-hashes | uv pip install -r -

    - name: Check dependencies with deptry
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: uv run --no-sync deptry .

    - name: Run tests with min dependencies
      shell: bash
      working-directory: ${{ inputs.package_dir }}
      run: |
        # Use --no-sync for min to prevent uv from "fixing" the versions
        uv run --no-sync pytest ${{ inputs.test_args }}