name: "Reusable Lint Workflow"

on:
  workflow_call:
    inputs:
      packages:
        description: 'JSON array of package directories to lint (e.g., ["unique_sdk", "unique_toolkit"])'
        required: true
        type: string
      python_version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(inputs.packages) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install workspace dependencies
        run: uv sync --extra dev

      - name: Run Ruff format check
        run: uv run --extra dev ruff format --check ${{ matrix.package }}/ --exclude ${{ matrix.package }}/site/ --exclude ${{ matrix.package }}/docs/

      - name: Run Ruff lint check
        run: uv run --extra dev ruff check ${{ matrix.package }}/ --exclude ${{ matrix.package }}/site/ --exclude ${{ matrix.package }}/docs/
