name: "[chore] Unique SDK - Enforce Changelog and Version Bump"

on: 
  pull_request:
    paths:
      - 'unique_sdk/**'
      - '!unique_sdk/**/docs/**'
      - '!unique_sdk/**/mkdocs.yaml'

jobs:
  validate-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper diff comparison

    - name: Validate changelog and version
      uses: ./.github/actions/validate-changelog
      with:
        package_name: "unique_sdk"