name: "GitHub · Policies · Verify · Pinned Actions"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - .github/actions/**

jobs:
  check-pinned-actions:
    name: Verify action SHAs are pinned
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Verify pinned actions
        uses: unique-ag/actions/github/policies/verify-pinned-actions@84a4f60c0a56daae108b22e096b72bb10f476d08 # main
