name: "[unique_follow_up_questions 📦] Publish to PyPI"

on:
  workflow_dispatch:
  push:
    # Both conditions must be met (AND logic):
    # 1. Push must be to main branch
    # 2. Push must include changes to follow_up_questions/** files
    paths:
      - 'follow_up_questions/**'
    branches:
      - main

env:
  PACKAGE_NAME: follow_up_questions
  PACKAGE_DIR: ./follow_up_questions
    
jobs:
  build-and-publish:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
            POETRY_VERSION='1.8.3'
            PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install poetry==$POETRY_VERSION

    - name: Install dependencies
      working-directory: ${{ env.PACKAGE_DIR }}
      run: poetry install

    - name: Build Package
      working-directory: ${{ env.PACKAGE_DIR }}
      run: poetry build
    
    - name: Publish to PyPI
      working-directory: ${{ env.PACKAGE_DIR }}
      run: poetry publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
    