name: "[unique_stock_ticker 📦] Publish to PyPI"

on:
  workflow_dispatch:
  push:
    # Both conditions must be met (AND logic):
    # 1. Push must be to main branch
    # 2. Push must include changes to postprocessors/stock_ticker/** files
    paths:
      - 'postprocessors/unique_stock_ticker/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/publish_stock_ticker_to_pypi.yaml'
      - '.github/workflows/_reusable_publish.yaml'
    branches:
      - main

env:
  PACKAGE_NAME: stock_ticker
  PACKAGE_DIR: ./postprocessors/unique_stock_ticker
    
jobs:
  publish:
    uses: ./.github/workflows/_reusable_publish.yaml
    with:
      package_name: unique-stock-ticker
      package_directory: unique_stock_ticker
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    