name: "[unique_internal_search 📦] Publish to PyPI"

on:
  workflow_dispatch:
  push:
    # Both conditions must be met (AND logic):
    # 1. Push must be to main branch
    # 2. Push must include changes to internal_search/** files
    paths:
      - 'tool_packages/unique_internal_search/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/publish_tool_internal_search_to_pypi.yaml'
      - '.github/workflows/_reusable_publish.yaml'
    branches:
      - main
    
jobs:
  publish:
    uses: ./.github/workflows/_reusable_publish.yaml
    with:
      package_name: unique-internal-search
      package_directory: tool_packages/unique_internal_search
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    