name: "[unique_orchestrator 📦] Publish to PyPI"

on:
  workflow_dispatch: # If you attempt to push the same version of a package to the Python Package Index (PyPI) multiple times, it will result in an error. PyPI enforces version uniqueness for packages to maintain consistency and prevent confusion among users.
  push:
    # Both conditions must be met (AND logic):
    # 1. Push must be to main branch
    # 2. Push must include changes to unique_orchestrator/** files
    # 3. Exclude docs-only and mkdocs config changes to avoid unnecessary publishes
    paths:
      - 'unique_orchestrator/**'
      - '!unique_orchestrator/**/docs/**'
      - '!unique_orchestrator/**/mkdocs.yaml'
    branches:
      - main

env:
  PACKAGE_DIR: ./unique_orchestrator

jobs:
  build-and-publish:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Publish to PyPI
      uses: ./.github/actions/publish-to-pypi-with-poetry
      with:
        package_dir: ${{ env.PACKAGE_DIR }}
        python_version: '3.12'
        pypi_token: ${{ secrets.PYPI_TOKEN }}
